correction version FRF (Answer issue 41)
scilus/nf-neuro pull request #47
Opened 2024-11-21 22:39 UTC by ThoumyreStanislas

#41

2024-11-21 22:49 UTC, ThoumyreStanislas commented
forgot to update snaps sorry

2024-11-21 22:58 UTC, AlexVCaron commented
Synthbet requires 8Gb of RAM and should be assigned a `bigmem` test runner, like easyreg

2024-11-22 00:58 UTC, ThoumyreStanislas commented
where is the tag "bigmem" in easyreg I don't remember and I don't find it @AlexVCaron

2024-11-22 02:06 UTC, AlexVCaron commented
[Here](https://github.com/scilus/nf-neuro/blob/main/.github%2Fworkflows%2Frun_checks_suite.yml#L155-L156), copy the two lines for easyreg and adapt for the name of the synthseg module

2024-11-22 02:23 UTC, ThoumyreStanislas commented
But it is already written just above the easyreg line @AlexVCaron

2024-11-22 02:51 UTC, AlexVCaron commented
I mean synthbet 😅 that was dumb, my bad !

2024-11-28 20:28 UTC, gagnonanthony submitted a review, later dismissed
LGTM! 🚀

2024-11-28 20:48 UTC, AlexVCaron requested changes

2024-11-28 20:48 UTC, AlexVCaron commented on modules/nf-neuro/reconst/frf/main.nf
Here, create a new `task.ext.precision` instead of hard baking the precision in the script. Set it to something like 8, 4 is a bit low for FRF since the values are in the range of 10^-4.

2024-11-28 21:13 UTC, AlexVCaron commented on modules/nf-neuro/reconst/frf/main.nf
> +    def precision = task.ext.precision ? "--precision " + task.ext.precision : "ssst"
```suggestion
    def precision = task.ext.precision ? "--precision " + task.ext.precision : ""
```

2024-11-28 21:13 UTC, AlexVCaron requested changes
Last little thing, but I'll fix it myself from the PR :wink:

2024-11-28 21:32 UTC, AlexVCaron approved these changes

2024-11-28 21:32 UTC, merged