#56 - make all preproc_t1 modules  optional
scilus/nf-neuro pull request #73
Opened 2024-12-12 16:58 UTC by ThoumyreStanislas

add an option in subworkflow preproc_t1 to make all preproc_t1 modules optional

2025-01-14 15:35 UTC, arnaudbore approved these changes
GTG

2025-01-14 18:50 UTC, AlexVCaron requested changes
Excellent work 🚀 I have a single comment, then LGTM !

2025-01-14 18:50 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_t1/main.nf
> +            bbox = []
Shouldn't those be `Channel.empty()` ?

2025-01-14 21:41 UTC, ThoumyreStanislas commented on subworkflows/nf-neuro/preproc_t1/main.nf
> +            bbox = []
yes, good point, I'll change it

2025-01-15 13:20 UTC, arnaudbore approved these changes
GTG again :)

2025-01-15 15:13 UTC, AlexVCaron approved these changes

2025-01-15 15:13 UTC, AlexVCaron commented
GJ 🚀

2025-01-15 15:36 UTC, merged