Fix external atlas use in `bundle_seg`
scilus/nf-neuro pull request #80
Opened 2024-12-12 20:16 UTC by gagnonanthony

When we changed how to provide a local copy of the `bundle_seg` atlas, we did not modify the path where the subworkflow fetched the files.

We don't have test data to include in the test suite, but I did try it locally, and everything runs smoothly.

2024-12-13 17:36 UTC, gagnonanthony commented
We should discuss what to do with the transform files as output from the registration scripts. As shown here, we might need to access only one of the two transformation files from the output channel. I'm not sure this is the best way to do it, because

1. It is not intuitive to extract (flatten, then back to list, then map).
2. It won't work if the user select rigid transform, since only one transformation file will be outputted.

I think we should separate the output files in individual channels. From my experience, this also facilitates the pipeline/subworkflows creation process. What do you think @AlexVCaron, @ThoumyreStanislas, @arnaudbore, @Manonedde ?

2024-12-13 18:12 UTC, AlexVCaron commented
Go for it ! I do agree it will make things easier. We implemented it that way to facilitate chaining transforms and prevent errors, but it just makes things harder and obscure.

2024-12-17 17:13 UTC, gagnonanthony commented
I've updated the registration scripts @AlexVCaron. However, I struggle to update the snap of `synthregistration` (I do not have 20GB of RAM available...). Could you update them?

2024-12-17 19:35 UTC, AlexVCaron commented
> I've updated the registration scripts @AlexVCaron. However, I struggle to update the snap of `synthregistration` (I do not have 20GB of RAM available...). Could you update them?

I'm on that !

2024-12-17 20:12 UTC, AlexVCaron commented
@rerun-checks

2024-12-18 19:06 UTC, ThoumyreStanislas approved these changes

2025-01-14 02:39 UTC, AlexVCaron commented
The tests pass ! But version files don't match for synthseg in the subworkflow ... so close, yet still not there yet 😅

2025-01-14 02:43 UTC, AlexVCaron commented
> The tests pass ! But version files don't match for synthseg in the subworkflow ... so close, yet still not there yet 😅 FYI, I assume you know this already, you can fake the version file at the correct versions and use `md5sum` to get the encoded descriptor.

2025-01-15 17:44 UTC, AlexVCaron requested changes
Once version files are fixed, and the few comments I left here, this will be GTG ! 🚢

2025-01-15 17:44 UTC, AlexVCaron commented on modules/nf-neuro/registration/synthregistration/tests/nextflow.config
The memory allocation should be inside the process selector

2025-01-15 20:19 UTC, AlexVCaron approved these changes
GTG on my end, once the tests pass 🤟🏻 Great job !

2025-01-15 20:50 UTC, merged