Add tractoflow subworkflow
scilus/nf-neuro pull request #82
Opened 2024-12-17 20:18 UTC by AlexVCaron

## Describe your changes

new subworkflow for tractoflow. I will lint and add tests soon

## List test packages used by your subworkflow

## Checklist before requesting a review

- Create the tool:
  - [x] Edit `./subworkflows/nf-neuro/<category>/<tool>/main.nf`
  - [x] Edit `./subworkflows/nf-neuro/<category>/<tool>/meta.yml`
- Generate the tests:
  - [x] Edit `./subworkflows/nf-neuro/<category>/<tool>/tests/main.nf.test`
  - [x] Run the tests to generate the `main.nf.test.snap` snapshots
- Ensure the syntax is correct :
  - [ ] Run `prettier` and `editorconfig-checker` to fix common syntax issues
  - [ ] Run `nf-core subworkflows lint` and fix all errors
  - [x] Ensure your variables have good, clear names

2025-01-16 20:22 UTC, arnaudbore reviewed
We are getting there !! We may need a discussion on teams to follow up with this discussion about params names and apart from a couple of comments everything seems ready.

2025-01-16 20:22 UTC, arnaudbore commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +  LOCAL TRACKING (dipy)
GPU implementation if 100% scilpy

2025-01-16 20:22 UTC, arnaudbore commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    fodf_pft_fit_step_size                          = 0.5
I think we we could, as much as possible and it still needs to make sense, keep the same var name we had with the original tractoflow.

2025-01-17 14:21 UTC, gagnonanthony requested changes
Amazing job! 💯 I wrote some comments, but they shouldn't be hard to solve!

2025-01-17 14:21 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/main.nf
> +            ch_topup_config
Is there a specific reason why you wrote the inputs as a pair rather than a vertical list? With the reverse images, it does make sense, but I think I would make it homogeneous with how we call the other subworkflows.

2025-01-17 14:21 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(REGISTRATION_FA.out.versions.first())
I think this adds a process that could be avoided. Unless I am missing something, the complete DTI process (lines 137-143) could be placed here, and the resulting FA map could be used for registration. This would avoid computing the FA twice and reduce runtime.

2025-01-17 14:21 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(TRACKING_LOCALTRACKING.out.versions.first())
Do we expect to run both tracking methods in a single run? We should use parameters to select which one we want to run.

2025-01-17 14:21 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
I think you can drop this line.

2025-01-17 14:21 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    fodf_pft_fit_step_size                          = 0.5
I agree with this, the simpler the parameters' names, the easier the user will understand how to use them. I think those are only for example purposes; when the subworkflow will be included in a pipeline, the `nextflow.config` and `modules.config` will need to be either copied or rewritten so they can be changed in the pipeline implementation of `tractoflow`.

2025-01-21 09:42 UTC, ThoumyreStanislas reviewed
Excellent work Alex! It's crazy to see it all finished. For my part, I don't have many comments, I agree with Arnaud and Anthony about the input nomenclature for FRF. Anthony's comment is relevant to the DTI_metrics module, which could be earlier to avoid calculating fa twice. But that's all, well done again! :rocket: :1st_place_medal:

2025-01-21 09:42 UTC, ThoumyreStanislas commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +        Structure: [ val(meta), path(probability_map) ]
For anatomical segmentation, you can also add a lesion mask as an input to complete the segmentation. It's optional.

2025-01-30 20:27 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(REGISTRATION_FA.out.versions.first())
Splitted the `reconstruction` section in two and lifted the RECONST_DTIMETICS process here

2025-01-30 20:31 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(TRACKING_LOCALTRACKING.out.versions.first())
I think so, I've boosted PFT tractograms with local tracking often. Max does it as well.

2025-01-30 20:36 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +  - nextflow.config : contains an example configuration for the subworkflow. Includes :
I can replace it with something clearer, like : Uses `includeConfig "modules.config"` to bind the parameters with the modules. There is a `includeConfig` directive at the bottom of the `nextflow.config` file.

2025-01-30 20:43 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +        Structure: [ val(meta), path(probability_map) ]
I've added the input and steps required to get the mask in diffusion space. Do you think the mask should be used anywhere in `PREPROC_T1` steps (like masking lesions in nlmeans or controlling N4) ?

2025-01-30 21:17 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    fodf_pft_fit_step_size                          = 0.5
Also, just for 2 seconds of pettiness, `pft_tracking_` is as long as `fodf_pft_fit_`, but the latter is more semantically sound and provides more information :tongue: but enough of that, I do agree

2025-01-30 21:35 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    fodf_pft_fit_step_size                          = 0.5
I've done a good pass on names. Tests will error out, I've not propagated the naming yet (it's time consuming). My logic : keep names as explicit as can be, but don't take too much space, and be closer to tractoflow. Tell me what you think about it.

2025-01-31 21:47 UTC, arnaudbore reviewed
Almost there, var names are getting better but I feel like I need it to work and test it through the nf-tractoflow to give me a better idea. Please make sure everything works between this PR and the repo nf-tractoflow so we can test it.

2025-01-31 21:47 UTC, arnaudbore commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    compute_pft                                     = true
This is not used and I would like the name to be run_pft, run_lt, run_fodf, and run_dti and finally run_registration so we are giving all the options for people to use this subworkflow as its max.

2025-01-31 21:48 UTC, arnaudbore commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    compute_pft                                     = true
i feel like if we already have a module to concatenate tractogram we should have a run_ensemble and combine both if asked.

2025-02-02 18:12 UTC, anroy1 commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(TRACKING_LOCALTRACKING.out.versions.first())
With the deprecation of the ext.when argument, does nextflow plan to replace this functionality? (Other than with if statements)

2025-02-03 01:20 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(TRACKING_LOCALTRACKING.out.versions.first())
The `ext` directive is not deprecated. It is just shunned upon by the **nf-core** community.

2025-02-04 19:49 UTC, AlexVCaron commented
Not ready, I needed to push to run tests on my big machine 😉

2025-02-05 16:01 UTC, ThoumyreStanislas reviewed
Perfect! I've got nothing to say about tractoflow as such, but I'm having trouble understanding how preproc dwi works.

2025-02-05 16:22 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
I don't have one yet. I haven't created a test for PREPROC_DWI. I can provide it in the next commit, once the current tests pass, along with one for Topup_Eddy as well.

2025-02-05 17:57 UTC, ThoumyreStanislas commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +        Structure: [ val(meta), path(probability_map) ]
I don't think it's necessary to add masks to other modules, just make sure that tracking masks are properly completed with lesion masks.

2025-02-05 18:09 UTC, arnaudbore approved these changes
We are getting there !!!

2025-02-05 19:18 UTC, anroy1 commented on subworkflows/nf-neuro/tractoflow/main.nf
> +        ch_versions = ch_versions.mix(TRACKING_LOCALTRACKING.out.versions.first())
Was specifically referring to the "when" statement, which to me seemed like the best way to imply discriminate tracking between tracking methods. But:
"Deprecated since version 24.10.0: Use conditional logic (e.g. if statement, [filter](https://www.nextflow.io/docs/latest/reference/operator.html#operator-filter) operator) in the calling workflow instead."
https://www.nextflow.io/docs/latest/process.html#when

2025-02-05 19:25 UTC, gagnonanthony commented on modules/nf-neuro/tracking/pfttracking/main.nf
> +        tuple val(meta), path("*__map_include.nii.gz")          , emit: includes
`include` and `exclude` are commands used by `nextflow`; the language server doesn't like it when we call outputs by those two terms (highlighted in red). I did the same thing in nf-pediatric.

2025-02-05 19:47 UTC, gagnonanthony submitted a review, later dismissed
Great job! 💯  I left some comments, but they don't really require changes.

2025-02-05 19:47 UTC, gagnonanthony commented on subworkflows/nf-neuro/preproc_dwi/main.nf
>          // ** Bet-crop DWI ** //
Out of curiosity, why `betcrop` is not optional?

2025-02-05 19:47 UTC, gagnonanthony commented on subworkflows/nf-neuro/preproc_dwi/main.nf
>          // ** Normalize DWI ** //
Same thing here, why `normalize` isn't optional?

2025-02-05 19:47 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/tests/main.nf.test
> +            assertAll(
From this list of assertions, i'm guessing that other than the simple files, it is not possible to have reproducible md5sum?

2025-02-05 20:33 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/tests/main.nf.test
> +            assertAll(
No, not after registration and BET using ANTs, sadly. we'd have to run on a single thread, but it's already taking an hour to execute the tests ...

2025-02-05 20:37 UTC, AlexVCaron commented on modules/nf-neuro/reconst/meanfrf/main.nf
> +        tuple val(label), path(frf_list)
It's the average in a "label" (wm, gm csf, a brain region ...), but I'm okay with `prefix`, so I'll change it

2025-02-05 20:38 UTC, AlexVCaron commented on modules/nf-neuro/tracking/pfttracking/main.nf
> +        tuple val(meta), path("*__map_include.nii.gz")          , emit: includes
thanks, I had forgotten about that one !

2025-02-05 20:39 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
>          // ** Bet-crop DWI ** //
I implemented the base options necessary to replicate the current tractoflow, no more.

2025-02-05 20:41 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/meta.yml
> +  - nextflow.config : contains an example configuration for the subworkflow. Includes :
Good ! I'll use just that

2025-02-05 20:43 UTC, gagnonanthony commented on subworkflows/nf-neuro/preproc_dwi/main.nf
>          // ** Bet-crop DWI ** //
That's perfect @AlexVCaron ! It can come in a future PR, I figured there was a similar reason behind this.

2025-02-05 20:44 UTC, gagnonanthony commented on subworkflows/nf-neuro/tractoflow/tests/main.nf.test
> +            assertAll(
Yeah, that's not surprising... Anyway we are already full-testing the subworkflows/modules, so let's go for the quickest tests possible!

2025-02-05 20:44 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
>          // ** Normalize DWI ** //
Same answer !:tongue:

2025-02-05 20:46 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
> +        dwi_n4              = ch_dwi_preproc                // channel: [ val(meta), dwi-after-n4 ]
If N4 is disabled, you'd get an error using `N4_DWI.out` because `image` is not defined in it.

2025-02-05 20:48 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
> +        dwi_n4              = ch_dwi_preproc                // channel: [ val(meta), dwi-after-n4 ]
But I understand that how it's implemented, we have a corner case if somehow decides to get the content of `dwi_n4` with N4 disabled. I'll split the channels per module, like in `PREPROC_T1`.

2025-02-05 20:49 UTC, arnaudbore commented on subworkflows/nf-neuro/preproc_dwi/main.nf
> +        dwi_n4              = ch_dwi_preproc                // channel: [ val(meta), dwi-after-n4 ]
Ok but dwi_n4 could not be N4 correct is a little bit misleading.

2025-02-05 20:50 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/tests/main.nf.test
> +            assertAll(
Yes, that was my hunch for now. I want to add a test with reverse phase images eventually, once the container is updated and we can run multithreaded Eddy.

2025-02-05 21:18 UTC, AlexVCaron commented on subworkflows/nf-neuro/preproc_dwi/main.nf
> +        dwi_n4              = ch_dwi_preproc                // channel: [ val(meta), dwi-after-n4 ]
Should be better now

2025-02-05 21:19 UTC, AlexVCaron commented on subworkflows/nf-neuro/tractoflow/nextflow.config
> +    compute_pft                                     = true
Let's put that in an issue

2025-02-06 14:15 UTC, gagnonanthony approved these changes

2025-02-06 14:19 UTC, arnaudbore approved these changes
GTG

2025-02-06 15:17 UTC, merged